version: '2'
services:
  debug:
    build: phpstorm/php-71-apache-xdebug
    ports:
     - "80:80"
    volumes:
      - .:/www
    environment:
        #change the line below with your IP address
        XDEBUG_CONFIG: remote_host=192.168.2.108
  sftp:
    image: phpstorm/sftp-server
    ports:
      - "2022:22"
    volumes:
  #   Please uncomment for Windows
  #     - C:/temp:/home/jetbrains/upload
  #   Please uncomment for macOS/Linux
      - /tmp:/home/jetbrains/upload
    command: jetbrains:jetbrains:1001