version: '2'
services:
  sftp:
    build: .
    ports:
     - "80:80"
    volumes:
      - .:/www
    environment:
        #change the line below with your IP address
        XDEBUG_CONFIG: remote_host=192.168.2.108